Config = {}

Config.scrollSpeed = 250 -- MILLISECONDS BETWEEN CHANGING OPTION

Config.menuOptions = { -- SET ALL DEFAULT MENU OPTIONS HERE:MENUSCALE(SET TEXT SCALE OF EACH MENU OPTION, BIGGER VALUE MEANS BIGGER TEXT), MENUFONT(SET TEXT FONT OF MENUS, DEFAULT GTA TEXT FONT OPTIONS),
  -- DISPLAYEDOPTIONSLIMIT(SET LIMIT OF MENU OPTIONS DISPLAYED, USE ODD VALUE, NO MS USAGE TESTED OVER 15 OPTIONS DISPLAYED),
  -- ALLOWCUSTOM(SET true TO ALLOW CLIENTS TO CUSTOMIZE THEIR OWN MENU OPTIONS USING COMMANDS, SET false TO HAVE CLIENTS USE DEFAULT MENU OPTIONS)
  menuScale = 0.75,
  menuFont = 4,
  displayedOptionsLimit = 7, -- USE ODD VALUE, WILL ONLY ALLOW ODD VALUES ANYWAY :S NO MS USAGE TESTED OVER 15 OPTIONS DISPLAYED
  allowCustom = true
}

Config.usableFonts = {[0] = true, [1] = true, [2] = true, [3] = false, [4] = true, [5] = false, [6] = true, [7] = true, [8] = true} -- SET ALL USABLE FONT VALUES HERE
-- IF YOU KNOW HOW TO ADD/REPLACE FONTS ETC PUT THEM HERE AND SET THEM TO = true

Config.keyBinds = { -- SET ALL MENU KEY BIND VALUES HERE:PREVIOUS OPTION(KEY TO MOVE TO "UP" MENU, BACKWARD THROUGH ELEMENTS), NEXT OPTION(KEY TO MOVE "DOWN" MENU, FORWARD THROUGH ELEMENTS),
  -- DECREASE VALUE(KEY TO MAKE SLIDER MENU VALUE LESS), INCREASE VALUE(KEY TO MAKE SLIDER MENU VALUE MORE), SELECT OPTION(KEY TO SELECT THE CURRENT MENU OPTION), CLOSE MENU(KEY TO BACK OUT OF AND CLOSE CURRENT MENU),
  -- DISABLEKEYBINDS(SET true TO DISABLE MENU KEYS WHILE USING A MENU, SET false TO ENABLE MENU KEYS WHILE USING A MENU(PROBABLY JUST KEEP FALSE :S))
  ['Previous Option'] = 172, -- ARROW UP/DPAD UP
  ['Next Option'] = 173, -- ARROW DOWN/DPAD DOWN
  ['Decrease Value'] = 174, -- ARROW LEFT/DPAD LEFT
  ['Increase Value'] = 175, -- ARROW RIGHT/DPAD RIGHT
  ['Select Option'] = 176, -- ENTER/LEFT MOUSE/A BUTTON
  ['Close Menu'] = 177, -- BACKSPACE/ESC/RIGHT MOUSE/B BUTTON
  DisableKeybinds = true,
}

Config.screenLocations = { -- SET ALL MENU ALIGNMENT SCREEN LOCATIONS HERE:KEY IS ALIGNMENT NAME, X IS LEFT/RIGHT PLACEMENT ON SCREEN, Y IS TOP/BOTTOM PLACEMENT ON SCREEN
  ['top-left'] = {x = 0.1, y = 0.2},
  ['left'] = {x = 0.1, y = 0.5},
  ['bottom-left'] = {x = 0.1, y = 0.8},
  ['top-center'] = {x = 0.4, y = 0.2},
  ['center'] = {x = 0.4, y = 0.5},
  ['bottom-center'] = {x = 0.4, y = 0.8},
  ['top-right'] = {x = 0.7, y = 0.2},
  ['right'] = {x = 0.7, y = 0.5},
  ['bottom-right'] = {x = 0.7, y = 0.8},
  ['custom'] = {x = 0.5, y = 0.5}
}